### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Ibtisam34** [umair-rao/Catalog-of-my-things#14]
-  In this activity, my team and I we prepared a Kanban board with a GitHub project. We prepared an almost empty template that we needed to copy. All tasks are assigned to a member among us.

 

**** Below are the team in this project
[Ayesha](https://github.com/shella12)
[Umair](https://github.com/umair-rao)
[Ibtisam](https://github.com/Ibtisam34)

_The link to kanban board below_
[Kanban](https://github.com/umair-rao/Catalog-of-my-things/projects/1)

**Comment by andgarzonmal** [comment]
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 Hi Team   ✋🏼 

#### Your project is excellent. You are almost done. However, there are some issues you should fix. Please fix them and your project will be approved.

___ 

### ♻️ Request changes ♻️

- [ ]  Please make sure all tasks are assigned to someone in your team 

![image](https://user-images.githubusercontent.com/95243996/221544225-eb69b82b-9c19-4397-bd5d-f41f8ec033d3.png)


### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by KayLemba** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hello  @TEAM    , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- No linter errors




Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
